python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 1 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-1.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 2 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-2.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 3 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-3.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 4 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-4.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 5 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-5.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 6 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-6.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 7 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-7.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 8 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-8.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 9 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-9.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 10 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-10.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 11 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-11.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 12 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-12.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 13 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-13.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 14 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-14.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 15 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-15.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 16 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-16.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 17 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-17.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 18 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-18.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 19 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-19.log
python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 20 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10-ensemble-20.log



# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 10 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 10 --ensemble 1 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-10.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 1 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 110 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 110 --ensemble 1 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-110.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 80 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 80 --ensemble 1 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-80.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 40 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 40 --ensemble 1 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-40.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 1 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-1.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 2 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-2.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 3 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-3.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 4 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-4.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 5 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-5.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 6 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-6.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 7 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-7.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 8 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-8.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 9 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-9.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 10 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-10.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 11 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-11.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 12 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-12.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 13 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-13.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 14 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-14.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 15 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-15.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 16 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-16.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 17 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-17.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 18 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-18.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 19 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-19.log
# python lstm/lstm_hysteretical.py --lr 0.001 --epochs 30000  --mu 0 --sigma 20 --units 0 --nb_plays 0 --points 0 --__units__ 64 --loss mle --force_train --diff-weights  --__sigma__ 20 --ensemble 20 --method stock --__activation__ tanh &> lstm.tanh.stock.sigma-20-ensemble-20.log
